<template>
  <div class="parent-wrapper">
    <div class="event-wrapper" v-if="event">
      <v-card-title>
        {{ event.title }}
      </v-card-title>

      <v-card-text style="white-space: pre-line">
        <v-img width="100%" class="rounded" v-bind:src="event.image"></v-img>
        <br />
        Hosts: <b>{{ event.hosts.join(", ") }}</b>
        <br />
        Time<b>: {{ event.time }}</b>
        <br />
        Location<b>: {{ event.location }}</b>
        <br />
        Categories<b>: {{ event.categories.join(", ") }}</b>
        <br />
        Description:<br />
        {{ event.description }}
        <div v-if="event.location != 'Online event' && event.location != ''">
          <iframe
            width="100%"
            height="280px"
            frameborder="0"
            class="mt-2 rounded"
            v-bind:src="
              'https://www.google.com/maps/embed/v1/place?key=AIzaSyCQMbSQjawwUF2loVgW5NX5HpDp8069-HU&q=' +
                event.location.replaceAll('&', '%26')
            "
            allowfullscreen
          >
          </iframe>
          <br />
          <b>Note: Google Maps location here is not always correct </b>
        </div>
      </v-card-text>
      <v-divider></v-divider>
      <v-card-actions>
        <v-btn
          color="background white--text"
          :href="event.link"
          target="_blank"
        >
          <span class="pr-1" v-if="!this.$vuetify.breakpoint.xs">facebook</span>
          <v-icon>mdi-facebook</v-icon>
        </v-btn>
        <v-btn
          color="background white--text"
          :href="
            'https://www.google.com/calendar/render?action=TEMPLATE&text=' +
              event.title +
              '&dates=' +
              event.start_time.replace(/:|-|Z/g, '') +
              '/' +
              event.end_time.replace(/:|-|Z/g, '') +
              '&details=' +
              'Generated by penhwonders.com%3Cbr%3E%3Cbr%3E' +
              event.description
                .substring(0, 920)
                .replaceAll('\n', '%3Cbr%3E')
                .replaceAll('&', '%26') +
              '&location=' +
              event.location +
              '&trp=false&sprop=&sprop=name:'
          "
          target="_blank"
          rel="nofollow"
        >
          <span class="pr-1" v-if="!this.$vuetify.breakpoint.xsOnly"
            >Calendar</span
          >
          <v-icon>mdi-calendar</v-icon>
        </v-btn>
        <v-btn
          color="background white--text"
          :href="event.ticket"
          target="_blank"
          v-if="event.ticket !== ''"
        >
          <span class="pr-1" v-if="!this.$vuetify.breakpoint.xs">Ticket</span>
          <v-icon>mdi-ticket</v-icon>
        </v-btn>
        <v-spacer></v-spacer>
        <router-link to="/"
          ><v-btn color="secondary" text> Home </v-btn></router-link
        >
      </v-card-actions>
    </div>
  </div>
</template>

<script>
export default {
  name: "Event",
  data() {
    return {
      // eventId: null,
    };
  },
  computed: {
    event() {
      return this.$store.state.allEvents.filter(
        (event) => event._id === this.$route.params.id
      )[0];
    },
  },
  metaInfo() {
    return {
      meta: [
        // Twitter Card
        { name: "twitter:card", content: "summary" },
        { name: "twitter:title", content: "Penhwonder" },
        {
          name: "twitter:description",
          content: "Come and check out this event!!!",
        },
        // Facebook OpenGraph
        { property: "og:title", content: "Penhwonder" },
        { property: "og:site_name", content: "penhwonder" },
        { property: "og:type", content: "website" },
        {
          property: "og:description",
          content: "Come and check out this event!!!",
        },
      ],
    };
  },
};
</script>

<style scoped>
.event-wrapper {
  margin: 0 auto;
  padding: 1rem;
  max-width: 700px;
}
</style>
